import Head from "next/head";
import { Button, Container, Typography } from "@mui/material";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Typography variant="h2" component="h2" sx={{fontWeight: 500}}>
          Get paid for your content
        </Typography>
        <Typography variant="h4" component="h4" color="text.secondary" >
          Register in a few simple steps
        </Typography>

        <Button variant="contained" color="primary" sx={{marginTop: "50px", marginBottom: "50px", marginRight: "25px", fontWeight: 600}} >
          Get Started&nbsp;<span aria-hidden="true">&rarr;</span>
        </Button>
        <Button variant="outlined" color="primary" sx={{marginTop: "50px", marginBottom: "50px", fontWeight: 600}} >
          Learn More&nbsp;<span aria-hidden="true">&rarr;</span>
        </Button>

        <Typography variant="h5" component="h5" sx={{marginBottom: "25px"}} >
          Proven Fits
        </Typography>
      </Container>
    </>
  );
}
